# Generated by Django 2.1.5 on 2019-02-10 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('rua', models.CharField(max_length=30, null=True)),
                ('bairro', models.CharField(max_length=30, null=True)),
                ('cidade', models.CharField(max_length=40, null=True)),
                ('estado_uf', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aluno.Pessoa')),
            ],
            bases=('aluno.pessoa',),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
