# Generated by Django 2.1.5 on 2019-02-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
