# Generated by Django 2.1.5 on 2019-02-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=1)),
                ('quanttidade_alunos', models.CharField(max_length=3)),
                ('turno', models.CharField(max_length=20)),
                ('professores', models.ManyToManyField(to='professor.Professor')),
            ],
        ),
    ]
